gestapart/urls.py
from django.conf.urls import url
from django.contrib import admin
from custodio import views as custodioView
from gastosServicios import views as GSView
from base import views as baseView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', baseView.index, name='index'),
    url(r'^$', baseView.custom_login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^Zona/', custodioView.Zona, name='Zona'),
    url(r'^TiposEquipajes/', custodioView.TiposEquipajesMantanedor, name='TiposEquipajes'),
    url(r'^TiposCustodia/', custodioView.TiposCustodiaMantenedor, name='TiposCustodia'),
    url(r'^Custodio/Ingresar', custodioView.IngresarCustodio, name='Custodio/Ingresar'),
    url(r'PdfView', custodioView.PdfForge, name='PdfView'),
    url(r'PendientesEntrega', custodioView.PendientesEntrega, name='PendientesEntrega'),
    url(r'^Custodio/Custodio', custodioView.VerEditarCustodio, name='Custodio/Custodio'),
    url(r'Extravios', custodioView.Extravios, name='Extravios'),
    url(r'Historico', custodioView.Historico, name='Historico'),
    url(r'^valida_dcto/', custodioView.validaDocumento, name='valida_dcto'),
    url(r'^AdminUsuarios/', baseView.createUser, name='AdminUsuarios'),
    url(r'^Custodio/Informes', custodioView.Informes, name='Custodio/Informes'),
    url(r'^Gastos_servicios/servicios', GSView.Servicios, name='Gastos_servicios/servicios'),
    url(r'^Gastos_servicios/tipos_gastos', GSView.TiposGastos, name='Gastos_servicios/tipos_gastos'),
    url(r'^Gastos_servicios/configurar_alertas', GSView.ConfigurarAlertas, name='Gastos_servicios/configurar_alertas'),
    url(r'^Gastos_servicios/moneda', GSView.Moneda, name='Gastos_servicios/moneda'),
]

gastosServicios/models.py
from django.db import models
from custodio.models import Empresa
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
# Create your models here.


class TipoConsumo(models.Model):
    nombre = models.CharField(max_length=30)
    shortname = models.CharField(max_length=5)
    descripcion = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.nombre


class Moneda(models.Model):
    tipo = models.CharField(max_length=30)
    iso = models.CharField(max_length=5)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.iso


class Servicio(models.Model): # Tipo de servicio y costo fijo o variable
    nombre = models.CharField(max_length=30)
    costo = models.IntegerField(null=True)
    variable = models.BooleanField
    moneda = models.ForeignKey(Moneda)
    porDefecto = models.BooleanField()
    descripcion = models.CharField(max_length=200)
    PrestadorNombre = models.CharField(max_length=50)
    PrestadorFono = models.CharField(null=True, max_length=9)
    PrestadorEmail = models.CharField(null=True, max_length=30)
    PrestadorNroCuenta = models.CharField(null=True, max_length=12)
    PrestadorRazonSocial = models.CharField(null=True, max_length=70)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.nombre


class Consumo(models.Model):
    descriptor = models.CharField(max_length=30)
    codigo = models.CharField(max_length=20, null=True)
    tipoConsumo = models.ForeignKey(TipoConsumo)
    servicios = models.ManyToManyField(Servicio, through='ConsumoServicios')
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.descriptor


class Periocidad(models.Model):
    nombre = models.CharField(max_length=30)
    periodo = models.IntegerField()  # cantidad de meses del periodo (ej. Mensual periodo = 1, trimestral periodo = 2)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.nombre


class ConsumoServicios(models.Model):
    consumo = models.ForeignKey(Consumo)
    servicio = models.ForeignKey(Servicio)
    is_mensual = models.BooleanField()  # si es mensual entonces especifica si es mensual, trimestral, anual
    periocidad = models.ForeignKey(Periocidad, null=True)
    dia_mes_pago = models.IntegerField(null=True) # si es mensual, trimestral o anual, debe especificar el dia de pago o dia de facturacion
    is_dias = models.BooleanField()  # en cambio si es por dias especificar los dias del periodo para el pago
    periocidad_dias = models.IntegerField(null=True)
    fecha_ini = models.DateField()
    fecha_ultimo = models.DateField(null=True)

    def __str__(self):
        return self.consumo.descriptor + ' - ' + self.servicio.nombre


class Parametro(models.Model):  ##PARAMETROS PARA CONSUMOS DE SERVICIOS
    alerta_dias = models.IntegerField()
    correo_alerta = models.CharField(max_length=30)
    empresa = models.ForeignKey(Empresa)


class PagoCunsumoServicio(models.Model):
    monto_pagado = models.IntegerField()
    is_pagado = models.BooleanField()
    fecha_pago = models.DateField()
    comentario = models.CharField(max_length=40, null=True)
    consumo_servicio = models.ForeignKey(ConsumoServicios)

gestapart/forms.py
from django import forms
from django.forms import ModelForm, inlineformset_factory
from custodio.models import *
from django.contrib.auth.forms import UserCreationForm

class ZonaForm(forms.ModelForm):

    class Meta:
        model = Zona
        fields = ['zona_nombre', 'capacidad', 'empresa']

class TiposEquipajesForm(forms.ModelForm):
    class Meta:
        model = EquipajeTipo
        fields = ['nombre', 'tamano', 'empresa']

class TiposCustidiaForm(forms.ModelForm):
    class Meta:
        model = CustodiaTipo
        fields = ['nombre', 'descripcion', 'empresa']

class CustodioForm(forms.ModelForm):
    class Meta:
        model = Custodio
        fields = ['pasajero', 'fecha_ingreso', 'comentario', 'custodia_tipo_id', 'extravio']

class EquipajesForm(forms.ModelForm):
    class Meta:
        model = Equipaje
        fields = ['equipaje_tipo_id', 'color', 'zona_id', 'comentario']
        exclude = ()

class DeleteCustodioForm(forms.ModelForm):
    class Meta:
        model = Custodio
        fields = ['id']

class UserAdminForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = {'username', 'first_name', 'last_name', 'email', 'password1', 'password2'}


EquipajesFormSet = inlineformset_factory(Custodio, Equipaje, form=EquipajesForm, extra=1)

class imageEmpresaSaveForm(forms.ModelForm):
    image = forms.FileField()
    class Meta:
        model = Empresa
        fields = {'image'}

gastosServicios/views.py
from django.shortcuts import render
from gastosServicios.models import *
from django.contrib.auth.decorators import login_required
# Create your views here.

def Servicios(request):
    coleccionServicios = Servicio.objects.filter(empresa__exact=request.session['empresaid'])
    return render(request, 'Gastos_servicios/servicios.html', {'coleccionServicios': coleccionServicios})


def TiposGastos(request):
    return render(request, 'Gastos_servicios/tipos_gastos.html', {'test':'test'})


def ConfigurarAlertas(request):
    return render(request, 'Gastos_servicios/configurar_alertas.html', {'test':'test'})


def Moneda(request):
    return render(request, 'Gastos_servicios/monedas.html', {'test':'test'})

templates/Gastos_servicios/configurar_alertas.html
{% extends "base_dash.html" %}
{% load static %}
{% block header %}
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/Rutina.js' %}"></script>
    <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% endif %} <strong>{{ message }}</strong>
        </div>
        {% endfor %}
    {% endif %}
ALERTAS

{{ test }}

{% endblock %}

templates/Gastos_servicios/monedas.html
{% extends "base_dash.html" %}
{% load static %}
{% block header %}
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/Rutina.js' %}"></script>
    <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% endif %} <strong>{{ message }}</strong>
        </div>
        {% endfor %}
    {% endif %}

MONEDAS
{{ test }}

{% endblock %}

templates/Gastos_servicios/servicios.html
{% extends "base_dash.html" %}
{% load static %}
{% block header %}
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/Rutina.js' %}"></script>
    <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% endif %} <strong>{{ message }}</strong>
        </div>
        {% endfor %}
    {% endif %}
<button type="button" class="btn btn-primary " data-toggle="modal" data-target=".add-servicio-modal"><span
            class="glyphicon glyphicon-plus"></span> Agregar servicio
    </button>

        <div class="modal fade add-servicio-modal" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Agregar nuevo servicio</h4>
                </div>
                <div class="modal-body">
                    <h4>LLene los campos requeridos</h4>
                    <form class="form-horizontal form-label-left" method="post" id="id_addUserForm">
                        {% csrf_token %}
                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_name">Nombre:<span class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input id="id_name" name="name" class="form-control col-md-7 col-xs-12"
                                       data-validate-length-range="6" data-validate-words="2" required="required"
                                       type="text">
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_costo">Costo (aprox):<span
                                    class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input id="id_costo" name="costo" class="form-control col-md-7 col-xs-12"
                                       data-validate-length-range="6" data-validate-words="2" required="required"
                                       type="text">
                            </div>
                        </div>
                        <div class="item form-group">
                            <input class="" id="id_porDefecto" name="porDefecto" type="checkbox">
                            <label title="Asina el costo aproximado como valor por defecto para el servicio (se puede modificar mas tarde)." class="control-label col-md-5 col-sm-3 col-xs-12" for="id_porDefecto">Valor por defecto? </label>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_last_name">Moneda:<span
                                    class="required">*</span>
                            </label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <select id="id_moneda" class="form-control col-md-7 col-xs-12" name="moneda">
                                </select>
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_PrestadorNombre">Nombre del prestador:</label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" id="id_PrestadorNombre" maxlength="50" name="PrestadorNombre" type="text">
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_PrestadorFono">Fono del prestador:</label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" id="id_PrestadorFono" maxlength="9" name="PrestadorFono" type="text">
                            </div>
                        </div>

                        <div class="item form-group">
                            <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_PrestadorEmail">Email prestador:</label>

                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" id="id_PrestadorEmail" maxlength="30" name="PrestadorEmail" type="text">
                            </div>
                        </div>

                       <div class="item form-group">
                               <label class="control-label col-md-4 col-sm-3 col-xs-12" for="id_PrestadorNroCuenta">Nro Cuenta Prestador:</label>
                            <div class="col-md-5 col-sm-6 col-xs-12">
                                <input class="form-control col-md-7 col-xs-12" id="id_PrestadorNroCuenta" maxlength="12" name="PrestadorNroCuenta" type="text">
                            </div>
                       </div>

                    </form>
                </div>


                <div class="modal-footer">
                    <button type="reset" form="id_addUserForm" class="btn btn-default" data-dismiss="modal">Cerrar
                    </button>
                    <button type="submit" form="id_addUserForm" class="btn btn-primary">Enviar</button>
                </div>

            </div>
        </div>
    </div>



    <div class="x_panel">
                  <div class="x_title">
                    <h2>Servicios disponibles<small>(gastos de servicios)</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">
                    <p>Editar o eliminar</p>
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>

                          <tr class="headings">

                            <th class="column-title">Nombre </th>
                            <th class="column-title">Capacidad</th>
                              <th class="column-title">Ocupados</th>
                            <th class="column-title">Accion </th>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>

                        </thead>

                        <tbody>

                        {% for servicio in coleccionServicios %}
                          <tr class="even pointer">
                            <td class=" ">{{ servicio.nombre }}</td>
                            <td class=" ">{{ servicio.descripcion }}</td>
                             <td class=" ">{{ servicio.PrestadorNombre }}</td>
                            <td class=" "><form method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" value="{{ servicio.id }}" name="iddelete">
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                            </form>
                            </td>
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>


                  </div>
                </div>


{% endblock %}

templates/Gastos_servicios/tipos_gastos.html
{% extends "base_dash.html" %}
{% load static %}
{% block header %}
    <script src="{% static 'js/bootbox.min.js' %}"></script>
    <script src="{% static 'js/Rutina.js' %}"></script>
    <link href="{% static 'css/bootstrap-toggle.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags %}
                <div class="alert alert-{{ message.tags }} alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% endif %} <strong>{{ message }}</strong>
        </div>
        {% endfor %}
    {% endif %}

TIPO GASTOS
{{ test }}

{% endblock %}