gestapart/urls.py
from django.conf.urls import url
from django.contrib import admin
from custodio import views as custodioView
from gastosServicios import views as GSView
from base import views as baseView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', baseView.index, name='index'),
    url(r'^$', baseView.custom_login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^Zona/', custodioView.Zona, name='Zona'),
    url(r'^TiposEquipajes/', custodioView.TiposEquipajesMantanedor, name='TiposEquipajes'),
    url(r'^TiposCustodia/', custodioView.TiposCustodiaMantenedor, name='TiposCustodia'),
    url(r'^Custodio/Ingresar', custodioView.IngresarCustodio, name='Custodio/Ingresar'),
    url(r'PdfView', custodioView.PdfForge, name='PdfView'),
    url(r'PendientesEntrega', custodioView.PendientesEntrega, name='PendientesEntrega'),
    url(r'^Custodio/Custodio', custodioView.VerEditarCustodio, name='Custodio/Custodio'),
    url(r'Extravios', custodioView.Extravios, name='Extravios'),
    url(r'Historico', custodioView.Historico, name='Historico'),
    url(r'^valida_dcto/', custodioView.validaDocumento, name='valida_dcto'),
    url(r'^AdminUsuarios/', baseView.createUser, name='AdminUsuarios'),
    url(r'^Custodio/Informes', custodioView.Informes, name='Custodio/Informes'),
    url(r'^Gastos_servicios/servicios', GSView.Servicios, name='Gastos_servicios/servicios'),
    url(r'^Gastos_servicios/tipos_gastos', GSView.TiposGastos, name='Gastos_servicios/tipos_gastos'),
    url(r'^Gastos_servicios/configurar_alertas', GSView.ConfigurarAlertas, name='Gastos_servicios/configurar_alertas'),
    url(r'^Gastos_servicios/moneda', GSView.Moneda, name='Gastos_servicios/moneda'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Empresa(models.Model):
    razonSocial = models.CharField(max_length=200)
    nombre = models.CharField(max_length=120)
    rut = models.CharField(max_length=10)
    image = models.FileField(upload_to='static/uploads/')
    abreviado = models.CharField(max_length=5)
    direccion = models.CharField(max_length=200)
    contactoTecnico = models.CharField(max_length=120, null=True)
    emailContactoTecnico = models.CharField(max_length=120, null=True)
    contactoComercial = models.CharField(max_length=120)
    emailContactoComercial = models.CharField(max_length=120)
    fono = models.CharField(max_length=10)

    def __str__(self):
        return self.nombre


class Sexo(models.Model):
    genero = models.CharField(max_length=30)

    def __str__(self):
        return self.genero


class Pais(models.Model):
    iso = models.CharField(max_length=2)
    nombre = models.CharField(max_length=80)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Paises"



class UserEmpresa(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.user.username + ' - ' + self.empresa.nombre

custodio/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from base.models import *
# Create your models here.

class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=30)
    nacionalidad = models.ForeignKey(Pais, null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = "Tipos de documentos"


class Pasajero(models.Model):
    nombres = models.CharField(max_length=80)
    apellidos = models.CharField(max_length=80)
    fullname = models.CharField(max_length=160)
    shortname = models.CharField(max_length=80)
    documento = models.CharField(max_length=20, db_index=True)
    tipo_documento = models.ForeignKey(TipoDocumento)
    nacionalidad = models.ForeignKey(Pais)
    email = models.CharField(max_length=80, null=False)
    telefono = models.CharField(max_length=20, null=False)
    sexo = models.ForeignKey(Sexo)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.shortname

    class Meta:
        verbose_name_plural = "Pasajeros"



class Zona(models.Model):
    zona_nombre = models.CharField(max_length=45, null=False)
    capacidad = models.IntegerField(default=0)
    empresa = models.ForeignKey(Empresa)

    class Meta:
        verbose_name_plural = "Zonas"

    def __str__(self):
        return self.zona_nombre


class EquipajeTipo(models.Model):
    nombre = models.CharField(max_length=45)
    tamano = models.CharField(max_length=45)
    empresa = models.ForeignKey(Empresa)

    class Meta:
        verbose_name_plural = "Tipos equipaje"

    def __str__(self):
        return self.nombre


class CustodiaTipo(models.Model):
    nombre = models.CharField(max_length=45)
    descripcion = models.CharField(max_length=200)
    empresa = models.ForeignKey(Empresa)

    class Meta:
        verbose_name_plural = "Tipos custodia"

    def __str__(self):
        return self.nombre + ' - ' + self.empresa.nombre


class Custodio(models.Model):
    pasajero = models.ForeignKey(Pasajero)
    fecha_ingreso = models.DateTimeField(null=False)
    fecha_entrega = models.DateTimeField(null=True)
    usuario_registra = models.CharField(max_length=125)
    usuario_entrega = models.CharField(max_length=125, null=True)
    comentario = models.CharField(max_length=200, null=True)
    extravio = models.BooleanField()
    custodia_tipo_id = models.ForeignKey(CustodiaTipo)
    codigo_barra = models.CharField(max_length=150, default='')
    entregado = models.BooleanField(default=False)
    empresa = models.ForeignKey(Empresa)

    class Meta:
        verbose_name_plural = "Custodios"

    def __str__(self):
        return self.codigo_barra

class Equipaje(models.Model):
    color = models.CharField(max_length=45)
    comentario = models.CharField(max_length=45, null=True)
    zona_id = models.ForeignKey(Zona, on_delete=models.CASCADE)
    equipaje_tipo_id = models.ForeignKey(EquipajeTipo)
    custodio_id = models.ForeignKey(Custodio) #custodio
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.color

    class Meta:
        verbose_name_plural = "Equipajes"

gastosServicios/models.py
from django.db import models
from custodio.models import Empresa
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
# Create your models here.


class TipoConsumo(models.Model):
    nombre = models.CharField(max_length=30)
    shortname = models.CharField(max_length=5)
    descripcion = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.nombre


class Moneda(models.Model):
    tipo = models.CharField(max_length=30)
    iso = models.CharField(max_length=5)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.iso


class Servicio(models.Model): # Tipo de servicio y costo fijo o variable
    nombre = models.CharField(max_length=30)
    costo = models.IntegerField(null=True)
    variable = models.BooleanField
    moneda = models.ForeignKey(Moneda)
    porDefecto = models.BooleanField()
    descripcion = models.CharField(max_length=200)
    PrestadorNombre = models.CharField(max_length=50)
    PrestadorFono = models.CharField(null=True, max_length=9)
    PrestadorEmail = models.CharField(null=True, max_length=30)
    PrestadorNroCuenta = models.CharField(null=True, max_length=12)
    PrestadorRazonSocial = models.CharField(null=True, max_length=70)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.nombre


class Consumo(models.Model):
    descriptor = models.CharField(max_length=30)
    codigo = models.CharField(max_length=20, null=True)
    tipoConsumo = models.ForeignKey(TipoConsumo)
    servicios = models.ManyToManyField(Servicio, through='ConsumoServicios')
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.descriptor


class Periocidad(models.Model):
    nombre = models.CharField(max_length=30)
    periodo = models.IntegerField()  # cantidad de meses del periodo (ej. Mensual periodo = 1, trimestral periodo = 2)
    empresa = models.ForeignKey(Empresa)

    def __str__(self):
        return self.nombre


class ConsumoServicios(models.Model):
    consumo = models.ForeignKey(Consumo)
    servicio = models.ForeignKey(Servicio)
    is_mensual = models.BooleanField()  # si es mensual entonces especifica si es mensual, trimestral, anual
    periocidad = models.ForeignKey(Periocidad, null=True)
    dia_mes_pago = models.IntegerField(null=True) # si es mensual, trimestral o anual, debe especificar el dia de pago o dia de facturacion
    is_dias = models.BooleanField()  # en cambio si es por dias especificar los dias del periodo para el pago
    periocidad_dias = models.IntegerField(null=True)
    fecha_ini = models.DateField()
    fecha_ultimo = models.DateField(null=True)

    def __str__(self):
        return self.consumo.descriptor + ' - ' + self.servicio.nombre


class Parametro(models.Model):  ##PARAMETROS PARA CONSUMOS DE SERVICIOS
    alerta_dias = models.IntegerField()
    correo_alerta = models.CharField(max_length=30)
    empresa = models.ForeignKey(Empresa)


class PagoCunsumoServicio(models.Model):
    monto_pagado = models.IntegerField()
    is_pagado = models.BooleanField()
    fecha_pago = models.DateField()
    comentario = models.CharField(max_length=40, null=True)
    consumo_servicio = models.ForeignKey(ConsumoServicios)

templates/PdfView.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/Zona.html
{% extends "base_dash.html" %}

{% block content %}

        <div class="x_panel">
                  <div class="x_title">
                    <h2>Agregar Zonas de almacenaje <small>(custodio)</small></h2>

                    <ul class="nav navbar-right panel_toolbox">
                    <!--- dropdown de ventana -->
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                      <p><code>0 significa infinito</code></p>
                    <form class="form-horizontal form-label-left" method="post">
                     {% csrf_token %}
                       <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nombre de zona <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input id="id_zona_nombre" name="zona_nombre" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" placeholder="ej. Bodega 32" required="required" type="text">
                        </div>
                      </div>

                        <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Capacidad <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                          <input id="id_capacidad" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2" name="capacidad" required="required" type="text" value="0">
                        </div>
                      </div>
                        <div class="ln_solid"></div>
                        <div class="col-md-6 col-md-offset-5">
                          <button id="send" type="submit" class="btn btn-success">Agregar</button>
                        </div>

                    </form>
                  </div>
                </div>

<!--- TABLA --->
        {% if messages %}
    {% for message in messages %}
     {% if message.tags %}
         <div class="alert alert-{{ message.tags }} alert-dismissable">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
     {% endif %} <strong>{{ message }}</strong>
        </div>
    {% endfor %}

{% endif %}
    <div class="x_panel">
                  <div class="x_title">
                    <h2>Zonas de Almacenaje<small>(custodio)</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>

                  <div class="x_content">
                    <p>Zonas disponibles</p>
                    <div class="table-responsive">
                      <table class="table table-striped jambo_table bulk_action">
                        <thead>

                          <tr class="headings">

                            <th class="column-title">Nombre </th>
                            <th class="column-title">Capacidad</th>
                              <th class="column-title">Ocupados</th>
                            <th class="column-title">Accion </th>
                            </th>
                            <th class="bulk-actions" colspan="7">
                              <a class="antoo" style="color:#fff; font-weight:500;">Bulk Actions ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
                            </th>
                          </tr>

                        </thead>

                        <tbody>

                        {% for zona in zonas %}
                          <tr class="even pointer">
                            <td class=" ">{{ zona.zona_nombre }}</td>
                            <td class=" ">{{ zona.capacidad }}</td>
                             <td class=" ">{{ zona.equipaje_set.count }}</td>
                            <td class=" "><form method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" value="{{ zona.id }}" name="iddelete">
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                            </form>
                            </td>
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>


                  </div>
                </div>


{% endblock %}

templates/base_dash.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}<title>Dashboard</title>{% endblock %}

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
    <!-- JQVMap -->
    <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="../index" class="site_title"><i class="fa fa-bed"></i>
                        <span>{{ request.session.empresa }}</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="../{{ request.session.imageurl }}" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>Bienvenido,</span>
                        <h2>{{ request.session.username }}</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3>Modulos</h3>
                        <ul class="nav side-menu">
                            <li><a><i class="fa fa-suitcase"></i> Custodio <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="../PendientesEntrega">Pendientes de entrega</a></li>
                                    <li><a href="../Custodio/Ingresar">Ingresar</a></li>
                                    <li><a href="../Extravios">Extravio</a></li>
                                    <li><a href="../Historico">Historico</a></li>
                                    <li><a href="../Custodio/Informes">Informes</a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-edit"></i>Mantenciones<span class="label label-success pull-right">Pronto!</span></a>
                                <!--- ULs -->
                            </li>
                            <li><a><i class="fa fa-desktop"></i>Gastos de servicios<span
                                    class="label label-success pull-right">Pronto!</span></a>
                                <!--- ULs -->
                            </li>
                        </ul>
                    </div>

                    {%  if perms.custodio.add_zona or  perms.custodio.add_equipajetipo or perms.custodio.add_custodiatipo %}
                        <div class="menu_section">
                            <h3>Parametros</h3>
                            <ul class="nav side-menu">
                                <li><a><i class="fa fa-cogs"></i>Custodio<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        {% if  perms.custodio.add_zona %}
                                        <li><a href="../Zona">Zonas de almacenaje</a></li>
                                        {% endif %}
                                        {% if  perms.custodio.add_equipajetipo %}
                                        <li><a href="../TiposEquipajes">Tipos de equipaje</a></li>
                                          {% endif %}
                                     {% if  perms.custodio.add_custodiatipo %}
                                        <li><a href="../TiposCustodia">Tipos de custodia</a></li>
                                         {% endif %}
                                    </ul>
                                    <li><a><i class="fa fa-cogs"></i>Gastos de servicios<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        {% if  perms.custodio.add_servicio %}
                                        <li><a href="../Gastos_servicios/servicios.html">Servicios</a></li>
                                        {% endif %}
                                        {% if  perms.custodio.add_tipo_consumo %}
                                        <li><a href="../Gastos_servicios/tipos_gastos.html">Tipos de gastos</a></li>
                                          {% endif %}
                                     {% if  perms.custodio.add_parametro %}
                                        <li><a href="../Gastos_servicios/configurar_alertas.html">Configurar alertas</a></li>
                                         {% endif %}
                                     {% if  perms.custodio.add_moneda %}
                                        <li><a href="../Gastos_servicios/monedas.html">Monedas</a></li>
                                         {% endif %}
                                    </ul>

                                </li>
                            </ul>
                        </div>

                    {% endif %}
                </div>
                <!-- /sidebar menu -->

                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Settings">
                        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Lock">
                        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Logout" href="../logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <i class="fa fa-user"></i>&nbsp;{{ request.session.username }}
                                <span class="fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li>
                                    <a href="javascript:;">
                                        <span><i class="fa fa-wrench pull-right"></i>Ajustes de cuenta</span>
                                    </a>
                                </li>
                            <!-- ACA COMPRUEBA SI ES ADMIN DE USUARIOS -->

                                {% if perms.auth.add_user %}
                                <li>
                                    <a href="../AdminUsuarios">
                                        <span><i class="fa fa-users pull-right"></i>Administrador</span>
                                    </a>
                                </li>
                                {% endif %}
                                <li><a href="../logout"><i class="fa fa-sign-out pull-right"></i>
                                Salir</a></li>
                            </ul>
                        </li>


                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->

        <div class="right_col" role="main" style="min-height: 923px;">
            {% block content %}{% endblock %}
            <!-- /page content -->
        </div>
        <!-- footer content -->
        <footer>
            <div class="pull-right">
                Administracion de servicios <a href="">GestApart</a>
            </div>
            <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
    </div>
</div>

<!-- jQuery -->
<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
<!-- Chart.js -->
<script src="{% static 'vendors/Chart.js/dist/Chart.min.js' %}"></script>
<!-- gauge.js -->
<script src="{% static 'vendors/gauge.js/dist/gauge.min.js' %}"></script>
<!-- bootstrap-progressbar -->
<script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
<!-- Skycons -->
<script src="{% static 'vendors/skycons/skycons.js' %}"></script>
<!-- Flot -->
<script src="{% static 'vendors/Flot/jquery.flot.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.time.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.stack.js' %}"></script>
<script src="{% static 'vendors/Flot/jquery.flot.resize.js' %}"></script>
<!-- Flot plugins -->
<script src="{% static 'vendors/flot.orderbars/js/jquery.flot.orderBars.js' %}"></script>
<script src="{% static 'vendors/flot-spline/js/jquery.flot.spline.min.js' %}"></script>
<script src="{% static 'vendors/flot.curvedlines/curvedLines.js' %}"></script>
<!-- DateJS -->
<script src="{% static 'vendors/DateJS/build/date.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'vendors/jqvmap/dist/jquery.vmap.js' %}"></script>
<script src="{% static 'vendors/jqvmap/dist/maps/jquery.vmap.world.js' %}"></script>
<script src="{% static 'vendors/jqvmap/examples/js/jquery.vmap.sampledata.js' %}"></script>
<!-- bootstrap-daterangepicker -->
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
{% block header %} {% endblock %}
<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $("#txtFechaIn").daterangepicker({
            singleDatePicker: true,
            singleClasses: "picker_2",
            timePicker24Hour: true,
            locale: {
                format: 'DD/MM/YYYY HH:mm'
            },
            timePicker: true
        })
    });

</script>
{% block footer %} {% endblock %}
</body>
</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
  <head>
    <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Login - GestApart</title>

    <!-- Bootstrap -->
    <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'vendors/nprogress/nprogress.css'%}" rel="stylesheet">
    <!-- Animate.css -->
    <link href="{% static 'vendors/animate.css/animate.min.css'%}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css'%}" rel="stylesheet">
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">
            <form method="post">
              <h1>Gest-Apart</h1>
              <div>
                  {% csrf_token %}
                <input type="text" class="form-control" placeholder="username" required="" name="username"/>
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Password" name="password" required="" />
              </div>
              <div>
                  <button type="submit" value="ingreso" class="btn btn-default submit">Entrar</button>
              </div>

              <div class="clearfix">
                              <h3>
                    <small style='color: #c12e2a'>{% if form.errors %}
                            {% for key,value in form.errors.items %}
                              <p>{{ value|escape }}</p>
                            {% endfor %}
                        {% endif %}</small>
            </h3>
              </div>

              <div class="separator">


                <div class="clearfix"></div>
                <br />

                <div>
                  <h1><i class="fa fa-bed"></i> Gestion de ApartHotel</h1>
                  <p>©2017 All Rights Reserved. VPLUS LTDA.</p>
                </div>
              </div>
            </form>
          </section>
        </div>


      </div>
    </div>
  </body>
</html>